---
name: QueryServer
version: 0.0.2
api: 5.0.0
main: NhanAZ\QueryServer\Main
src-namespace-prefix: NhanAZ\QueryServer
website: https://github.com/NhanAZ
description: Query information of other servers
commands:
  query:
    permission: queryserver.cmd
    description: Querying server information (API v3 or direct query)
    usage: "/query <domain/ip[:port]> [port] (e.g. /query test.pmmp.io 19132)"
    permission-message: §e>§c You do not have permission to use this command!

permissions:
  queryserver.cmd:
    default: op
    description: Allow querying other servers information
...
